### ISSUE TITLE
Device compatibility issue

### ISSUE THREAD

**Issue by kedsnaik** [surikov/midi-sounds-react#10]
Hello Sir,
         I have used the midi sounds package to build a website. The website works properly in all the browsers in android, windows and MacBook devices but the play button doesn't seem to produce any sound in Apple device like iPhone or iPad. Should this be an issue with the library. Please help me solve this. 

Thank you.

**Comment by surikov** [comment]
iPhone has trigger at the side. Try to switch it. This trigger mutes speaker for Web Audio API sounds but other sounds (audio from Youtube for example) works despite the trigger state. Also Web Audio still plays via earphones.

This is very strange behaviour of iPhone.

**Comment by kedsnaik** [comment]
It worked. Thank you very much sir.
