### ISSUE TITLE
Legato or Portamento

### ISSUE THREAD

**Issue by raamkum** [surikov/midi-sounds-react#11]
Hi, 

Is it possible to code songs using legato and portamento using midi-sounds-react, if so how do I go about doing this?

I couldn't find any example of portamento or legato?  Let me know!

Thanks!

**Comment by surikov** [comment]
example of pitch slide from parent project
https://surikov.github.io/webaudiofont/examples/fx.html

**Comment by raamkum** [comment]
Pitch slide is not a part of midi sound react right?

**Comment by surikov** [comment]
midi-sounds-react uses WebAudioFont
WebAudioFont uses Web Audio API
Web Audio API implements sliding of any parameter by origin
