### ISSUE TITLE
Using Pitch bend in queueWaveTable function.

### ISSUE THREAD

**Issue by kedsnaik** [surikov/midi-sounds-react#12]
Hello Sir,

 I have used your code to implement pitch bend using queueWaveTable function. The parameter description for **slides says array of pitch bend** which I assume values to be in the format of [1,2,3] etc.. I used an array in that place and I am not getting the desired output of pitch bend. **Here is the function that I am talking about :** 
function play(){
	player.queueWaveTable(audioContext, audioContext.destination
	, _tone_0250_SoundBlasterOld_sf2, **1, 12*4+7,4,1, [1,3]**);
	return false;
}
**I got the above information from https://surikov.github.io/webaudiofont/.** 
From what I understand, this tone should start after 1 second, be playing for 4 seconds and there should be pitch bend. Could you please correct me if I am wrong and let me know the right syntax for using pitch bend. 

Thank you,
Kedar Naik

**Comment by surikov** [comment]
read project wiki
https://github.com/surikov/webaudiofont/wiki/2.1.-queueWaveTable
see example of slide
https://surikov.github.io/webaudiofont/examples/mixer.html
