### ISSUE TITLE
Has anyone been able to implement this with NextJS?

### ISSUE THREAD

**Issue by helmutgranda** [surikov/midi-sounds-react#13]
I am converting a personal - for fun - project from React into NextJS, as I am new to NextJS I am having issues with the MIDISounds component being added to the page since NextJS does not have access to the window or root.

I am also trying with WebAudioFont library and facing a few challenges that is why I am asking about MIDISounds working on NextJS.

**Comment by surikov** [comment]
MIDISounds API uses Web Audio API.
Web Aaudio API uses browser to make sound.
You can not produce a sound on server side.

**Comment by helmutgranda** [comment]
Thanks @surikov, here is the version I put together with NextJS with WebAudioFontPlayer.js

https://csb-next-music-director.helmutgranda.vercel.app/
