### ISSUE TITLE
Is it possible to hide the MIDISOUNDS logo?

### ISSUE THREAD

**Issue by weiwei-ww** [surikov/midi-sounds-react#2]
Hi, I noticed that I could change the volume when I clicked on the logo. I wonder if I do not need this function on my website, is it possible to hide it?

**Comment by surikov** [comment]
use https://github.com/surikov/webaudiofont for non-UI functions.

**Comment by weiwei-ww** [comment]
Thanks for helping. However, I am building a midi player using React. I have tried using [webaudiofont](https://github.com/surikov/webaudiofont) but I could not load the soundfont data in React.

**Comment by surikov** [comment]
MIDI player example
https://surikov.github.io/webaudiofont/examples/midiplayer.html

create new issue in WebAudioFont project if you have question about WebAudioFont project.
