### ISSUE TITLE
AudioContext raising error due to Chrome policy change

### ISSUE THREAD

**Issue by magmukendi** [surikov/midi-sounds-react#20]
Hello @surikov 

I have been playing around with the midi-sounds-react, but I have noticed this `warning` on chrome browser: `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page`. 
![image](https://github.com/user-attachments/assets/f78e7439-27cf-4ded-ad96-df4314ebfc9a)

This warning is related to the new policy from chrome that is giving more control to the user. You can read more about it [here](https://developer.chrome.com/blog/autoplay/#webaudio) .

The warning is coming because the AudioContext is used before any gesture or event from the user, hence creating the AudioContext in a suspended state. We will need to resume the AudioContext by using `AudioContext.resume()` first before being able to use start the audioContext in any way.

I am not sure if this repo is still maintained but I would like to work, or help you fix this little warning.
There is also a thread on StackOverflow about this. You can find it [here](https://stackoverflow.com/questions/55026293/google-chrome-javascript-issue-in-getting-user-audio-the-audiocontext-was-not)

**Comment by surikov** [comment]
Look to parent project at
https://github.com/surikov/webaudiofont

It uses resume() if you start playing before user interaction.

Dont't create AudioContext at page load to avoid warnings in browser console.

**Comment by magmukendi** [comment]
See that makes more sense. 

Thanks for clarifying.

And thanks for making this open source
