### ISSUE TITLE
add new sounds to the project

### ISSUE THREAD

**Issue by camiloperezv** [surikov/midi-sounds-react#4]
Hi, I want to buy a VST of a piano sound to give my project a realistic touch. I'm wondering if I can play this custom sounds using your project.

Regards

**Comment by surikov** [comment]
midi-sounds-react uses instruments from WebAudioFont. See 
https://github.com/surikov/webaudiofont#custom-samples 
about custom samples creation.

You need to know about zones, ADSR envelopes, pitch correction, loop points etc.
The most of VSTi vendor prevent from extraction of samples from their commercial products.
WebAudioFont consists about of 80 pianos already.

**Comment by x267wu** [comment]
Sorry to bump this, but does the above mean that in order to use custom samples, we need to upload them to WebAudioFont so that midi-sounds-react can use them? Is there a way to do that privately?

**Comment by surikov** [comment]
You can create private instruments. Open
https://github.com/surikov/webaudiofont
read about custom samples
