### ISSUE TITLE
Can I Microtune the MIDI sounds?

### ISSUE THREAD

**Issue by kornaros** [surikov/midi-sounds-react#5]
Dear Mr Surikov. I am trying to write a simple code like yours
https://surikov.github.io/midi-sounds-react-examples/examples/midi-sounds-example10/build/
but with different pitches than the normal ones, for purpose of chanting.  For example, I need E4 to sound exactly  5/4 higher than D4. Is it possible?  Best regards, Kornaros (kornaros at aegean dot gr)

**Comment by surikov** [comment]
define pitch as float value.

D4 is 2+12*4=50
D4+5/4 is 50+5/4=51.25

**Comment by kornaros** [comment]
Dear Surikov Sergey! Thank you for the time you spend for me! 

Your answer give me much hope! But I dont understand your answer. I don't know where to put this new value. Could you please send a very simple code with one play button and sound: 584. Choir Aahs: Ensemble,(at  pitch 51.25 for D4) to see the general mechanism? 

Greetings, from the very  hot Samos(island of Greece)

Charalampos
________________________________________
Από: Srgy Surkv [notifications@github.com]
Στάλθηκε: Πέμπτη, 13 Ιουνίου 2019 12:14 μμ
Προς: surikov/midi-sounds-react
Κοιν.: Kornaros Charalampos; Author
Θέμα: Re: [surikov/midi-sounds-react] Can I Microtune the MIDI sounds? (#5)

define pitch as float value.

D4 is 2+12*4=50
D4+5/4 is 50+5/4=51.25

**Comment by surikov** [comment]
open source of example 1
change
this.midiSounds.playChordNow(3, [60], 2.5);
to
this.midiSounds.playChordNow(3, [60+5/4], 2.5);

its all.

**Comment by kornaros** [comment]
Dear Surikov Sergey!

I am just reading your tutorial in

https://www.npmjs.com/package/midi-sounds-react

As I told you a long time ago,  I am trying to make a microtuning midi keyboard using your nice  React. 

If I am not wrong,  the function playChordNow does not support  changing the base frequency i.e 440 for A4.

Is it possible to make a simple piano that the user could be able to change this basic frequency 440  to any other value (for all keys)?

Best regards,

Charalampos

________________________________________
Από: Srgy Surkv ***@***.***
Στάλθηκε: Πέμπτη, 13 Ιουνίου 2019 4:43 μμ
Προς: surikov/midi-sounds-react
Κοιν.: Kornaros Charalampos; Author
Θέμα: Re: [surikov/midi-sounds-react] Can I Microtune the MIDI sounds? (#5)

open source of example 1
change
this.midiSounds.playChordNow(3, [60], 2.5);
to
this.midiSounds.playChordNow(3, [60+5/4], 2.5);

its all.
