### ISSUE TITLE
Is it possible to use this without implementing the MIDISounds component

### ISSUE THREAD

**Issue by 2dareis2do** [surikov/midi-sounds-react#7]
Is it possible to implement this with out the MIDISounds component? I would like to control the  sounds from my store. AFAICT this sets up this.midiSounds when rendering <MIDISounds ref={(ref) => (this.midiSounds = ref)} appElementName="root" drums={[0]}. Is it possible to access without rendering this component?

**Comment by jkc909** [comment]
A workaround would be to wrap the component in a hidden div

**Comment by surikov** [comment]
Use CSS do hide <div class="MIDISounds">
