### ISSUE TITLE
How to play contineous sound

### ISSUE THREAD

**Issue by Arokia16** [surikov/midi-sounds-react#8]
Hi how to play below pitch

```
let pitch =[48, 50, 52, 54, 55, 57, 59, 60];
let instrument =73;
```

play and stop. I tried 

`this.midiSounds.playChordNow(48, [73], 2);`

**Comment by surikov** [comment]
Use long duration or look to source of example
https://surikov.github.io/midi-sounds-react-examples/examples/midi-sounds-example10/build/
